refactor(naming): change organization/users naming
vtex-apps/organizations pull request #10
Opened 2020-12-16 15:18 UTC by gsasouza

#### What does this PR do? \*

#### How to test it? \*

#### Describe alternatives you've considered, if any. \*

#### Related to / Depends on \*

2020-12-16 15:22 UTC, Klynger requested changes
Could you add a link to a workspace and how to test it just for us to see that nothing is breaking?

2020-12-16 21:12 UTC, Klynger submitted a review, later dismissed

2020-12-16 21:12 UTC, Klynger commented
If you're going to launch a version you should add the changelog too

2020-12-18 13:10 UTC, lucasecdb reviewed
missing small section in changelog 😅 otherwise lgtm

2020-12-18 13:10 UTC, lucasecdb commented on CHANGELOG.md
> +- Change labels, use `My Organization` / `organization` instead of `My users`/`users`
```suggestion
## [Unreleased]
### Changed
- Update labels to use `My Organization` / `organization` instead of `My users`/`users`
```

2020-12-18 13:12 UTC, merged